apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: kc-postgres
    literals:
      - password=$KEYCLOAK_POSTGRES_PASSWORD
      - postgres-password=$KEYCLOAK_POSTGRES_PASSWORD
generatorOptions:
  disableNameSuffixHash: true
