{{- if eq (getenv "INGRESS_CLASS") "nginx" }}
ingress:
  enabled: true
  className: "nginx"
  annotations:
    {{- range $key, $value := (datasource "annotations") }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
  hosts:
    - host: eoapi.{{ getenv "INGRESS_HOST" }}
      paths:
        - path: /manager(/|$)(.*)
          pathType: ImplementationSpecific
  {{- if eq ( getenv "HTTP_SCHEME" ) "https" }}
  tls:
    - secretName: "eoapi-tls"
      hosts:
        - eoapi.{{ getenv "INGRESS_HOST" }}
  {{- end }}
{{- else if eq (getenv "INGRESS_CLASS") "apisix" }}
ingress:
  enabled: false
{{- else }}
ingress:
  enabled: false
{{- end }}
resources:
  requests:
    memory: "1Gi"
    cpu: "1"
  limits:
    memory: "4Gi"
    cpu: "4"
publicUrl: {{ getenv "HTTP_SCHEME" }}://{{ getenv "EOAPI_PUBLIC_HOST" }}/manager/
stacApi: {{ getenv "HTTP_SCHEME" }}://{{ getenv "EOAPI_PUBLIC_HOST" }}/stac/
stacBrowser: {{ getenv "HTTP_SCHEME" }}://{{ getenv "EOAPI_PUBLIC_HOST" }}/browser/
primaryColor: "#005ACD"
secondaryColor: "#048A81"
appTitle: "EOEPCA+ STAC Manager"
appDescription: "Manage STAC collections and items on the EOEPCA+ platform"
{{- if eq (getenv "DATA_ACCESS_ENABLE_IAM") "yes" }}
oidc:
  authority: {{ getenv "HTTP_SCHEME" }}://{{ getenv "KEYCLOAK_HOST" }}/realms/{{ getenv "REALM" }}
  clientId: {{ getenv "EOAPI_CLIENT_ID" }}
{{- end }}
volumes:
  - name: branding
    configMap:
      name: stac-manager-branding
volumeMounts:
  - name: branding
    mountPath: /app/packages/client/dist/meta
