apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: opa-keycloak-client
    literals:
      - client_id: "opa"
      - client_secret: ${OPA_CLIENT_SECRET}
generatorOptions:
  disableNameSuffixHash: true
