stacture:
  image:
    tag: v0.0.8

  env:
    - name: DEBUG
      value: "true"
    - name: STACTURE_TERRAVIS_URL
      value: http://stacture-terravis:8080

  ingress:
    enabled: true
    className: ${INGRESS_CLASS}
    annotations:
${DATA_ACCESS_INGRESS_ANNOTATIONS}
    hosts:
      - host: stacture.${INGRESS_HOST}
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - stacture.${INGRESS_HOST}
        secretName: data-access-stacture-tls

  config:
    terravis_url: http://stacture-terravis:8080
    title: Stacture API
    apis:
      maps: true
      coverages: true
      wms_config:
        projections:
          - 4326
          - 3857
          - 3035
    collections:
      sentinel-2-l2a:
        coverage:
          default:
            - "TCI_10m"
        source:
          type: stac-api
          href: $HTTP_SCHEME://eoapi.${INGRESS_HOST}/stac/
          collection: sentinel-2-l2a
          extra:
            properties:
              renders:
                trc:
                  assets:
                    - trc
                  rescale:
                    - [-100, 1500]
                    - [25, 1500]
                    - [75, 1500]
                ndvi:
                  assets:
                    - ndvi
                  rescale:
                    - [-1, 1]
                  colormap_name: viridis
                scl:
                  assets:
                    - scl
            assets:
              trc:
                title: True color image
                type: "image/tiff; application=geotiff; profile=cloud-optimized"
                roles:
                  - visual
                  - data
                  - virtual
                href: "#/assets/trc"
                vrt:hrefs:
                  - key: B04
                    href: "#/assets/B04_10m"
                  - key: B03
                    href: "#/assets/B03_10m"
                  - key: B02
                    href: "#/assets/B02_10m"
              ndvi:
                roles:
                  - virtual
                  - data
                  - index
                href: "#/assets/ndvi"
                vrt:hrefs:
                  - key: B04
                    href: "#/assets/B04_10m"
                  - key: B08
                    href: "#/assets/B08_10m"
                title: "Normalized Difference Vegetation Index"
                vrt:algorithm: "band_arithmetic"
                vrt:algorithm_opts:
                  expression: (B08-B04)/(B08+B04)
                  rescale:
                    - [-1.0, 1.0]
        map:
          default_style: default
          styles:
            default:
              render: trc
            trc:
              render: trc
            ndvi:
              render: ndvi
            scl:
              render: scl

terravis:
  image:
    tag: v0.0.8
  env:
    - name: CPL_VSIL_CURL_ALLOWED_EXTENSIONS
      value: .TIF,.TIFF,.tif,.tiff,.xml,.jp2,.jpg,.jpeg,.png,.nc
    - name: AWS_ACCESS_KEY_ID
      value: ${S3_ACCESS_KEY}
    - name: AWS_SECRET_ACCESS_KEY
      value: ${S3_SECRET_KEY}
    - name: AWS_S3_ENDPOINT
      value: ${S3_HOST}
    - name: AWS_VIRTUAL_HOSTING
      value: "FALSE"
    - name: AWS_HTTPS
      value: "FALSE"
    - name: AWS_REGION
      value: default