existingSecret: minio-auth
replicas: 2
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: '600'
    ${CLUSTER_ISSUER_ANNOTATION}
  path: /
  hosts:
    - minio.${INGRESS_HOST}
  tls:
    - secretName: minio-tls
      hosts:
        - minio.${INGRESS_HOST}
consoleIngress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: '600'
    ${CLUSTER_ISSUER_ANNOTATION}
  path: /
  hosts:
    - console.minio.${INGRESS_HOST}
  tls:
    - secretName: minio-console-tls
      hosts:
        - console.minio.${INGRESS_HOST}
resources:
  requests:
    memory: 1Gi
persistence:
  storageClass: ${DB_STORAGE_CLASS}
  size: 50Gi
buckets:
  - name: eoepca
  - name: cache-bucket
  - name: gitlab-backup-storage
  - name: gitlab-tmp-storage
  - name: gitlab-lfs-storage
  - name: mlopbb-mlflow-sharinghub
  - name: mlopbb-sharinghub

{{- if .Values.clusterIssuer }}
clusterIssuer: ${CLUSTER_ISSUER}
{{- else }}
clusterIssuer: ""
{{- end }}