# values-opensearch.yaml

persistence:
  size: 12Gi
  enabled: false

replicas: 2

sysctl:
  enabled: false

sysctlInit:
  enabled: true

extraEnvs:
  - name: DISABLE_INSTALL_DEMO_CONFIG
    value: "true"

secretMounts:
  - name: certs
    secretName: opensearch-tls-certificate
    path: /usr/share/opensearch/config/esnode

config:
  opensearch.yml: |
    cluster.name: opensearch-cluster

    network.host: 0.0.0.0

    plugins:
      security:
        nodes_dn:
          - 'CN=resource-health-opensearch.svc.cluster.local'
        ssl:
          transport:
            pemcert_filepath: esnode/tls.crt
            pemkey_filepath: esnode/tls.key
            pemtrustedcas_filepath: esnode/ca.crt
            enforce_hostname_verification: false
          http:
            enabled: true
            pemcert_filepath: esnode/tls.crt
            pemkey_filepath: esnode/tls.key
            pemtrustedcas_filepath: esnode/ca.crt
            clientauth_mode: OPTIONAL
        allow_unsafe_democertificates: false
        allow_default_init_securityindex: true
        # authcz:
        #   admin_dn:
        #     - CN=kirk,OU=client,O=client,L=test,C=de
        audit.type: internal_opensearch
        enable_snapshot_restore_privilege: true
        check_snapshot_restore_write_privileges: true
        restapi:
          roles_enabled: ["all_access", "security_rest_api_access"]
        system_indices:
          enabled: true
          indices:
            [
              ".opendistro-alerting-config",
              ".opendistro-alerting-alert*",
              ".opendistro-anomaly-results*",
              ".opendistro-anomaly-detector*",
              ".opendistro-anomaly-checkpoints",
              ".opendistro-anomaly-detection-state",
              ".opendistro-reports-*",
              ".opendistro-notifications-*",
              ".opendistro-notebooks",
              ".opendistro-asynchronous-search-response*",
            ]

securityConfig:
  enabled: true
  path: "/usr/share/opensearch/config/opensearch-security"
  config:
    dataComplete: false
    data:
      config.yml: |
        _meta:
          type: "config"
          config_version: 2

        config:
          dynamic:
            kibana:
              multitenancy_enabled: true
              server_username: 'dashboards-client.resource-health-opensearch.svc.cluster.local'
              index: '.opensearch-dashboards'
            do_not_fail_on_forbidden: false

            http:
              anonymous_auth_enabled: false
            authc:
              basic_internal_auth_domain:
                description: "Authenticate via HTTP Basic against internal users database"
                http_enabled: true
                transport_enabled: true
                order: 2
                http_authenticator:
                  type: basic
                  challenge: true
                authentication_backend:
                  type: intern
              clientcert_auth_domain:
                description: "Authenticate via SSL client certificates"
                http_enabled: true
                transport_enabled: false
                order: 1
                http_authenticator:
                  type: clientcert
                  config:
                    username_attribute: cn
                  challenge: false
                authentication_backend:
                  type: noop

      internal_users.yml: |
        _meta:
          type: "internalusers"
          config_version: 2

        ## TODO: Remove this user
        ${SENSMETRY_USERNAME}:
          hash: ${SENSMETRY_PASSWORD}
          reserved: true
          backend_roles:
            - "admin"
          description: "Temporary admin user (Delete me)"

      # roles.yml: |-

      roles_mapping.yml: |
        _meta:
          type: "rolesmapping"
          config_version: 2

        all_access:
          reserved: false
          backend_roles:
            - "admin"
          users:
            - "sensmetry"
            - "otel-collector.resource-health-opensearch.svc.cluster.local"
          description: "Maps admin to all_access"

        kibana_server:
          reserved: true
          hidden: false
          backend_roles: []
          hosts: []
          users:
            - "dashboards-client.resource-health-opensearch.svc.cluster.local"
          and_backend_roles: []

      # action_groups.yml: |-
      # tenants.yml: |-