apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oeo
  namespace: openeo-geotrellis
  annotations:
    kubernetes.io/ingress.class: {{ getenv "INGRESS_CLASS" }}
    {{- range $key, $value := (datasource "annotations") }}
    {{ $key }}: "{{ $value }}"
    {{- end }}

    {{- if eq (getenv "INGRESS_CLASS") "apisix" }}
    k8s.apisix.apache.org/enable-cors: "true"
    k8s.apisix.apache.org/http-to-https: "true"
    {{- end }}
spec:
  ingressClassName: {{ getenv "INGRESS_CLASS" }}
  rules:
    - host: openeo.{{ getenv "INGRESS_HOST" }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: openeo-geotrellis-openeo-sparkapplication
                port:
                  number: 50001
  tls:
    - hosts:
        - openeo.{{ getenv "INGRESS_HOST" }}
      secretName: openeo-tls
