apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oeo
  namespace: openeo-geotrellis
  annotations:
    kubernetes.io/ingress.class: ${INGRESS_CLASS}
${CUSTOM_INGRESS_ANNOTATIONS}
    k8s.apisix.apache.org/enable-cors: "true"
    k8s.apisix.apache.org/http-to-https: "true"
spec:
  ingressClassName: ${INGRESS_CLASS}
  rules:
    - host: openeo.$INGRESS_HOST
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: openeo-geotrellis-openeo-sparkapplication
                port:
                  number: 50001
  tls:
    - hosts:
        - openeo.$INGRESS_HOST
      secretName: openeo-tls
