#!/usr/bin/env bash

ORIG_DIR="$(pwd)"
cd "$(dirname "$0")"
BIN_DIR="$(pwd)"

onExit() {
  cd "${ORIG_DIR}"
}
trap onExit EXIT

PUSH="${1:-false}"

docker build --pull -t eoepca/mkdocs-material .

if [ "$PUSH" = "push" ]; then
  docker push eoepca/mkdocs-material
fi
