#!/usr/bin/env bash

ORIG_DIR="$(pwd)"
cd "$(dirname "$0")"
BIN_DIR="$(pwd)"

onExit() {
  cd "${ORIG_DIR}"
}
trap onExit EXIT

source ./creodias-options

cluster_name="eoepca"

./local-deploy/eoepca/eoepca.sh apply "${cluster_name}" "${public_ip}" "${domain}"
# ./local-deploy/eoepca/data-access.sh apply "${domain}"
# ./local-deploy/eoepca/user-profile.sh apply "${public_ip}" "${domain}"
