#!/usr/bin/env bash

ORIG_DIR="$(pwd)"
cd "$(dirname "$0")"
BIN_DIR="$(pwd)"

onExit() {
  cd "${ORIG_DIR}"
}
trap onExit EXIT

# run mike
docker run --name mike --rm -it \
  -v ${PWD}:/docs \
  -v ${HOME}/.ssh:/root/.ssh \
  -v ${SSH_AUTH_SOCK}:/ssh-agent \
  -e SSH_AUTH_SOCK=/ssh-agent \
  --entrypoint=mike \
  eoepca/mkdocs-material \
  "$@"

# clean-up
sudo rm -rf site
sudo chown -R $(id -u):$(id -g) .git
