#!/usr/bin/env bash

ORIG_DIR="$(pwd)"
cd "$(dirname "$0")"
BIN_DIR="$(pwd)"

onExit() {
  cd "${ORIG_DIR}"
}
trap onExit EXIT

# publish
docker run --name mkdocs-deploy --rm -it \
  -v ${PWD}:/docs \
  -v ${HOME}/.ssh:/root/.ssh \
  -v ${SSH_AUTH_SOCK}:/ssh-agent \
  -e SSH_AUTH_SOCK=/ssh-agent \
  -e GIT_COMMITTER_NAME="$(git config --get user.name)" \
  -e GIT_COMMITTER_EMAIL="$(git config --get user.email)" \
  --entrypoint=mike \
  eoepca/mkdocs-material \
  deploy --push --update-aliases current latest

# clean-up
sudo rm -rf site
sudo chown -R $(id -u):$(id -g) .git
