apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Prerequisites
  - https://raw.githubusercontent.com/EOEPCA/workspace/refs/tags/v2025.06.05/setup/prerequisites/init/functions.yaml
  - https://raw.githubusercontent.com/EOEPCA/workspace/refs/tags/v2025.06.05/setup/prerequisites/init/providers.yaml
  - https://raw.githubusercontent.com/EOEPCA/workspace/refs/tags/v2025.06.05/setup/prerequisites/main/crd-storage.yaml
  - https://raw.githubusercontent.com/EOEPCA/workspace/refs/tags/v2025.06.05/setup/prerequisites/main/crd-workspace.yaml
  - https://raw.githubusercontent.com/EOEPCA/workspace/refs/tags/v2025.06.05/setup/prerequisites/main/csi-rclone.yaml
  - https://raw.githubusercontent.com/EOEPCA/workspace/refs/tags/v2025.06.05/setup/prerequisites/main/eso.yaml
  - https://raw.githubusercontent.com/EOEPCA/workspace/refs/tags/v2025.06.05/setup/prerequisites/main/providerConfigs.yaml
  - https://raw.githubusercontent.com/EOEPCA/workspace/refs/tags/v2025.06.05/setup/prerequisites/main/rbac.yaml
  # Storage Minio
  - https://raw.githubusercontent.com/EOEPCA/workspace/refs/tags/v2025.06.05/setup/storage-minio/init/providers.yaml
  - https://raw.githubusercontent.com/EOEPCA/workspace/refs/tags/v2025.06.05/setup/storage-minio/main/composition.yaml
  - https://raw.githubusercontent.com/EOEPCA/workspace/refs/tags/v2025.06.05/setup/storage-minio/main/providerConfigs.yaml
  # Either HostCluster or vCluster...
  # ...HostCluster
  - https://raw.githubusercontent.com/EOEPCA/workspace/refs/tags/v2025.06.05/setup/workspace-hostcluster/init/providers.yaml
  - https://raw.githubusercontent.com/EOEPCA/workspace/refs/tags/v2025.06.05/setup/workspace-hostcluster/main/composition.yaml
  # ...vCluster
  # - https://raw.githubusercontent.com/EOEPCA/workspace/refs/tags/v2025.06.05/setup/workspace-vcluster/init/providers.yaml
  # - https://raw.githubusercontent.com/EOEPCA/workspace/refs/tags/v2025.06.05/setup/workspace-vcluster/main/composition.yaml
  # - https://raw.githubusercontent.com/EOEPCA/workspace/refs/tags/v2025.06.05/setup/workspace-vcluster/main/providerConfigs.yaml
  # - https://raw.githubusercontent.com/EOEPCA/workspace/refs/tags/v2025.06.05/setup/workspace-vcluster/main/rbac.yaml
  - generated-environment.yaml

patches:
# Storage Minio
- target:
    kind: ProviderConfig
    name: provider-minio
  patch: |
    - op: replace
      path: /spec/minioURL
      value: https://minio.{{ getenv "INGRESS_HOST" }}
# HostCluster
- target:
    kind: Composition
    name: workspace
  patch: |
    - op: replace
      path: /spec/pipeline/2/input/resources/8/base/spec/forProvider/manifest/spec/storageClassName
      value: {{ getenv "STORAGE_CLASS" }}
