fullnameOverride: workspace-api
service:
  port: 8181
authAudience: "{{ getenv "WORKSPACE_API_CLIENT_ID" }}"
image:
  tag: 2.2.0
  pullPolicy: Always
ingress:
  enabled: false
prefixForName: ws
endpoint: "{{ getenv "S3_ENDPOINT" }}"
region: "{{ getenv "S3_REGION" }}"
forwardedAllowIps: "*"
sessionMode: "auto"
useVcluster: "true"
gunicornWorkers: "4"
uiMode: "ui"
