apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sh
  namespace: sharinghub
  annotations:
    {{- range $key, $value := (datasource "annotations") }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
spec:
  ingressClassName: {{ getenv "INGRESS_CLASS" }}
  rules:
    - host: sharinghub.{{ getenv "INGRESS_HOST" }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sharinghub
                port:
                  number: 8000
  {{- if eq ( getenv "HTTP_SCHEME" ) "https" }}
  tls:
    - hosts:
        - sharinghub.{{ getenv "INGRESS_HOST" }}
      secretName: sh-tls
  {{- end }}
