image:
  repository: eoepca/sharinghub
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: "nginx"
  annotations:
    ${CLUSTER_ISSUER_ANNOTATION}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 10g
  hosts:
    - host: sharinghub.${INGRESS_HOST}
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: sharinghub-tls
      hosts:
        - sharinghub.${INGRESS_HOST}

config: |-
  server:
    allowed-origins:
      - $HTTP_SCHEME://eoepca.readthedocs.io
    session:
      secret-key: "${SHARINGHUB_SESSION_SECRET}"
  gitlab:
    url: $HTTP_SCHEME://gitlab.${INGRESS_HOST}
    allow-public: true
  s3:
    enable: true
    bucket: ${S3_BUCKET}
    region: us-east-1
    endpoint: ${S3_ENDPOINT}
  mlflow:
    type: mlflow-sharinghub
    url: $HTTP_SCHEME://sharinghub.${INGRESS_HOST}/mlflow