global:
  redis:
    passSecret:
      name: tyk-redis
      keyName: redis-password

tyk-gateway:
  gateway:
    service:
      type: ClusterIP
    ingress:
      enabled: true
      className: apisix
      annotations:
        kubernetes.io/ingress.class: apisix
        ${CLUSTER_ISSUER_ANNOTATION}
        k8s.apisix.apache.org/http-to-https: "true"
      hosts:
        - host: tyk-gateway.${INGRESS_HOST}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - tyk-gateway.${INGRESS_HOST}
          secretName: tyk-gateway-tls
