{
 "title": "Kubernetes / Physical View",
 "tags": [ "baseline" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
   },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(kube_node_info{cluster=~\"$cluster\"}, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{cluster=~\"$cluster\", job=\"kube-state-metrics\", node=~\"$node\", resource=\"cpu\"})",
     "legendFormat": "max capacity"
    },
    {
     "expr": "sum(kube_node_status_allocatable{cluster=~\"$cluster\", job=\"kube-state-metrics\", node=~\"$node\", resource=\"cpu\"})",
     "legendFormat": "max allocatable"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=~\"$cluster\", node=~\"$node\", container!=\"\", image!=\"\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(max by (cluster, namespace, pod, container)(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{cluster=~\"$cluster\", node=~\"$node\"})) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", cluster=~\"$cluster\", node=~\"$node\", resource=\"cpu\"}) by (pod)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=~\"$cluster\", node=~\"$node\", container!=\"\", image!=\"\"}[$__rate_interval])) by (pod) / sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", cluster=~\"$cluster\", node=~\"$node\", resource=\"cpu\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=~\"$cluster\", node=~\"$node\", resource=\"cpu\"}) by (pod)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=~\"$cluster\", node=~\"$node\", container!=\"\", image!=\"\"}[$__rate_interval])) by (pod) / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=~\"$cluster\", node=~\"$node\", resource=\"cpu\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{cluster=~\"$cluster\", job=\"kube-state-metrics\", node=~\"$node\", resource=\"memory\"})",
     "legendFormat": "max capacity"
    },
    {
     "expr": "sum(kube_node_status_allocatable{cluster=~\"$cluster\", job=\"kube-state-metrics\", node=~\"$node\", resource=\"memory\"})",
     "legendFormat": "max allocatable"
    },
    {
     "expr": "sum(max by (cluster, namespace, pod, container)(node_namespace_pod_container:container_memory_working_set_bytes{cluster=~\"$cluster\", node=~\"$node\", container!=\"\"})) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{cluster=~\"$cluster\", job=\"kube-state-metrics\", node=~\"$node\", resource=\"memory\"})",
     "legendFormat": "max capacity"
    },
    {
     "expr": "sum(kube_node_status_allocatable{cluster=~\"$cluster\", job=\"kube-state-metrics\", node=~\"$node\", resource=\"memory\"})",
     "legendFormat": "max allocatable"
    },
    {
     "expr": "sum(max by (cluster, namespace, pod, container)(node_namespace_pod_container:container_memory_rss{cluster=~\"$cluster\", node=~\"$node\", container!=\"\"})) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=~\"$cluster\", node=~\"$node\", container!=\"\", image!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", cluster=~\"$cluster\", node=~\"$node\", resource=\"memory\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=~\"$cluster\", node=~\"$node\", container!=\"\", image!=\"\"}) by (pod) / sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", cluster=~\"$cluster\", node=~\"$node\", resource=\"memory\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=~\"$cluster\", node=~\"$node\", resource=\"memory\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=~\"$cluster\", node=~\"$node\", container!=\"\", image!=\"\"}) by (pod) / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=~\"$cluster\", node=~\"$node\", resource=\"memory\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=~\"$cluster\", node=~\"$node\", container!=\"\", image!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_cache{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=~\"$cluster\", node=~\"$node\", container!=\"\", image!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_swap{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=~\"$cluster\", node=~\"$node\", container!=\"\", image!=\"\"}) by (pod)"
    }
   ]
  }
 ]
}