apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: Client
metadata:
  name: eoapi
  namespace: iam-management
spec:
  providerConfigRef:
    name: provider-keycloak
    kind: ProviderConfig
  forProvider:
    realmId: {{ getenv "REALM" }}
    name: eoapi
    accessType: PUBLIC
    clientId: {{ getenv "EOAPI_CLIENT_ID" }}
    standardFlowEnabled: true
    implicitFlowEnabled: true
    directAccessGrantsEnabled: true # allow for now to simplify testing
    serviceAccountsEnabled: false
    oauth2DeviceAuthorizationGrantEnabled: true
    rootUrl: {{ getenv "HTTP_SCHEME" }}://eoapi.{{ getenv "INGRESS_HOST" }}
    webOrigins:
    - '*'
    validRedirectUris:
    - '*'
---
apiVersion: role.keycloak.m.crossplane.io/v1alpha1
kind: Role
metadata:
  name: stac-editor
  namespace: iam-management
spec:
  providerConfigRef:
    name: provider-keycloak
    kind: ProviderConfig
  forProvider:
    realmId: {{ getenv "REALM" }}
    name: stac_editor
    clientIdRef:
      name: eoapi
      policy:
        resolution: Required
---
apiVersion: group.keycloak.m.crossplane.io/v1alpha1
kind: Group
metadata:
  name: data-access-admin
  namespace: iam-management
spec:
  providerConfigRef:
    name: provider-keycloak
    kind: ProviderConfig
  forProvider:
    realmId: {{ getenv "REALM" }}
    name: data-access-admin
---
apiVersion: group.keycloak.m.crossplane.io/v1alpha1
kind: Roles
metadata:
  name: data-access-admin
  namespace: iam-management
spec:
  providerConfigRef:
    name: provider-keycloak
    kind: ProviderConfig
  forProvider:
    realmId: {{ getenv "REALM" }}
    groupIdRef:
      name: data-access-admin
      policy:
        resolution: Required
    roleIdsRefs:
    - name: stac-editor
      policy:
        resolution: Required
