expose:
  ingress:
    annotations:
      kubernetes.io/ingress.class: apisix
      ${CLUSTER_ISSUER_ANNOTATION}
      k8s.apisix.apache.org/http-to-https: "true"
      k8s.apisix.apache.org/upstream-read-timeout: "600s"
    hosts:
      core: harbor.${INGRESS_HOST}
  tls:
    enabled: true
    certSource: secret
    secret:
      secretName: "harbor-tls"

persistence:
  persistentVolumeClaim:
    registry:
      storageClass: ${STORAGE_CLASS}
    chartmuseum:
      storageClass: ${STORAGE_CLASS}
    jobservice:
      storageClass: ${STORAGE_CLASS}
    database:
      storageClass: ${STORAGE_CLASS}
    redis:
      storageClass: ${STORAGE_CLASS}
    trivy:
      storageClass: ${STORAGE_CLASS}

externalURL: ${HTTP_SCHEME}://harbor.$INGRESS_HOST
harborAdminPassword: ${HARBOR_ADMIN_PASSWORD}

chartmuseum:
  enabled: false
trivy:
  enabled: false
notary:
  enabled: false
