expose:
  ingress:
    annotations:
      kubernetes.io/ingress.class: {{ getenv "INGRESS_CLASS" }}
      {{- range $key, $value := (datasource "annotations") }}
      {{ $key }}: "{{ $value }}"
      {{- end }}
    hosts:
      core: harbor.{{ getenv "INGRESS_HOST" }}
  tls:
    enabled: true
    certSource: secret
    secret:
      secretName: "harbor-tls"

persistence:
  persistentVolumeClaim:
    registry:
      storageClass: {{ getenv "STORAGE_CLASS" }}
    chartmuseum:
      storageClass: {{ getenv "STORAGE_CLASS" }}
    jobservice:
      storageClass: {{ getenv "STORAGE_CLASS" }}
    database:
      storageClass: {{ getenv "STORAGE_CLASS" }}
    redis:
      storageClass: {{ getenv "STORAGE_CLASS" }}
    trivy:
      storageClass: {{ getenv "STORAGE_CLASS" }}

externalURL: {{ getenv "HTTP_SCHEME" }}://harbor.{{ getenv "INGRESS_HOST" }}
harborAdminPassword: {{ getenv "HARBOR_ADMIN_PASSWORD" }}

chartmuseum:
  enabled: false
trivy:
  enabled: false
notary:
  enabled: false
