{{- if eq (getenv "INGRESS_CLASS") "apisix" }}
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: registration-api
  namespace: resource-registration
spec:
  ingressClassName: apisix
  http:
  - name: registration-api
    match:
      hosts:
        - registration-api.{{ getenv "INGRESS_HOST" }}
      paths:
        - /*
    backends:
      - serviceName: registration-api-service
        servicePort: 80
    plugins:
      - name: cors
        enable: true
{{- if eq (getenv "RESOURCE_REGISTRATION_ENABLE_OIDC") "yes" }}
      - name: openid-connect
        enable: true
        config:
          client_id: "{{ getenv "RESOURCE_REGISTRATION_IAM_CLIENT_ID" }}"
          client_secret: "{{ getenv "RESOURCE_REGISTRATION_IAM_CLIENT_SECRET" }}"
          session:
            secret: "{{ getenv "RESOURCE_REGISTRATION_APISIX_SESSION_SECRET" }}"
          discovery: "{{ getenv "HTTP_SCHEME" }}://{{ getenv "KEYCLOAK_HOST" }}/realms/{{ getenv "REALM" }}/.well-known/openid-configuration"
          realm: "{{ getenv "REALM" }}"
          use_jwks: true
          bearer_only: false
          set_access_token_header: true
          access_token_in_authorization_header: true
      - name: authz-keycloak
        enable: true
        config:
          client_id: "{{ getenv "RESOURCE_REGISTRATION_IAM_CLIENT_ID" }}"
          client_secret: "{{ getenv "RESOURCE_REGISTRATION_IAM_CLIENT_SECRET" }}"
          discovery: "{{ getenv "HTTP_SCHEME" }}://{{ getenv "KEYCLOAK_HOST" }}/realms/{{ getenv "REALM" }}/.well-known/uma2-configuration"
          lazy_load_paths: true
          ssl_verify: false
{{- end }}
{{- if eq ( getenv "HTTP_SCHEME" ) "https" }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registration-api-tls
  namespace: resource-registration
spec:
  dnsNames:
    - registration-api.{{ getenv "INGRESS_HOST" }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ getenv "CLUSTER_ISSUER" }}
  secretName: registration-api-tls
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: registration-api-tls
  namespace: resource-registration
spec:
  ingressClassName: apisix
  hosts:
    - registration-api.{{ getenv "INGRESS_HOST" }}
  secret:
    name: registration-api-tls
    namespace: resource-registration
{{- end }}

{{- else }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registration-api
  namespace: resource-registration
  annotations:
    {{- range $key, $value := (datasource "annotations") }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
spec:
  ingressClassName: {{ getenv "INGRESS_CLASS" }}
  rules:
    - host: registration-api.{{ getenv "INGRESS_HOST" }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: registration-api-service
                port:
                  number: 80
  {{- if eq ( getenv "HTTP_SCHEME" ) "https" }}
  tls:
    - hosts:
        - registration-api.{{ getenv "INGRESS_HOST" }}
      secretName: registration-api-tls
  {{- end }}
{{- end }}