{{- if eq (getenv "OPERATIONS_ENABLE_IAM") "yes" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alerting
  namespace: operations
  annotations:
    kubernetes.io/ingress.class: {{ getenv "INGRESS_CLASS" }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    {{- range $key, $value := (datasource "annotations") }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
spec:
  ingressClassName: {{ getenv "INGRESS_CLASS" }}
  rules:
    - host: alerting.{{ getenv "INGRESS_HOST" }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: keep-oauth2-proxy
                port:
                  number: 80
  {{- if eq (getenv "HTTP_SCHEME") "https" }}
  tls:
    - hosts:
        - alerting.{{ getenv "INGRESS_HOST" }}
      secretName: alerting-tls
  {{- end }}
{{- else }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alerting-api
  namespace: operations
  annotations:
    kubernetes.io/ingress.class: {{ getenv "INGRESS_CLASS" }}
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    {{- range $key, $value := (datasource "annotations") }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
spec:
  ingressClassName: {{ getenv "INGRESS_CLASS" }}
  rules:
    - host: alerting.{{ getenv "INGRESS_HOST" }}
      http:
        paths:
          - path: /v2/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: keep-backend
                port:
                  number: 8080
          - path: /websocket/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: keep-websocket
                port:
                  number: 6001
  {{- if eq (getenv "HTTP_SCHEME") "https" }}
  tls:
    - hosts:
        - alerting.{{ getenv "INGRESS_HOST" }}
      secretName: alerting-tls
  {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alerting-frontend
  namespace: operations
  annotations:
    kubernetes.io/ingress.class: {{ getenv "INGRESS_CLASS" }}
    {{- range $key, $value := (datasource "annotations") }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
spec:
  ingressClassName: {{ getenv "INGRESS_CLASS" }}
  rules:
    - host: alerting.{{ getenv "INGRESS_HOST" }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: keep-frontend
                port:
                  number: 3000
  {{- if eq (getenv "HTTP_SCHEME") "https" }}
  tls:
    - hosts:
        - alerting.{{ getenv "INGRESS_HOST" }}
      secretName: alerting-tls
  {{- end }}
{{- end }}
