apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring
  namespace: operations
  annotations:
    kubernetes.io/ingress.class: {{ getenv "INGRESS_CLASS" }}
    {{- range $key, $value := (datasource "annotations") }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
spec:
  ingressClassName: {{ getenv "INGRESS_CLASS" }}
  rules:
    - host: monitoring.{{ getenv "INGRESS_HOST" }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: kube-prometheus-stack-grafana
                port:
                  number: 80
  {{- if eq (getenv "HTTP_SCHEME") "https" }}
  tls:
    - hosts:
        - monitoring.{{ getenv "INGRESS_HOST" }}
      secretName: monitoring-tls
  {{- end }}