# Resource Health values-template.yaml



mockapi:
  image:
    repository: docker.io/tilowiklundsensmetry/mock_service
    pullPolicy: IfNotPresent
    tag: "v0.0.1"
  serviceType: ClusterIP
  containerPort: 5000
  servicePort: 5000
  replicaCount: 2
  tls:
    commonName: mockapi.resource-health.svc.cluster.local
    issuerRef:
      kind: ClusterIssuer
      name: ${INTERNAL_CLUSTER_ISSUER}

healthchecks:
  checks:
    - name: hourly-mockapi-check
      image:
        repository: docker.io/tilowiklundsensmetry/healthcheck
        pullPolicy: IfNotPresent
        tag: "v0.0.4"
      schedule: "@hourly"
      requirements: "https://gist.githubusercontent.com/Jonas-Puksta-Sensmetry/cffc6a422d5bf5af7c4718ec75888950/raw/7e3a24902abd220bd5b3c12c7b3758185db5b13d/requirements.txt"
      script: "https://gist.githubusercontent.com/Jonas-Puksta-Sensmetry/cffc6a422d5bf5af7c4718ec75888950/raw/7e3a24902abd220bd5b3c12c7b3758185db5b13d/test_stuff.py"
      userid: alice
      env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: https://opentelemetry-collector.resource-health-opensearch.svc.cluster.local:4317
        - name: MOCK_API_HOST
          value: http://resource-health-mockapi:5000

    - name: daily-trivial-check
      image:
        repository: docker.io/tilowiklundsensmetry/healthcheck
        pullPolicy: IfNotPresent
        tag: "v0.0.4"
      ## Every day at 08:00
      schedule: "0 8 * * *"
      requirements: "https://gist.githubusercontent.com/Jonas-Puksta-Sensmetry/cffc6a422d5bf5af7c4718ec75888950/raw/7e3a24902abd220bd5b3c12c7b3758185db5b13d/requirements.txt"
      script: "https://gist.githubusercontent.com/tilowiklundSensmetry/74dea6500a5bd0b8bbce551249eb6786/raw/f7a614be2809576c4b4b0f3fcc1a1d34ac6af789/trivial_check.py"
      userid: bob
      env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: https://opentelemetry-collector.resource-health-opensearch.svc.cluster.local:4317

  tls:
    commonName: healthchecks.resource-health.svc.cluster.local
    issuerRef:
      kind: ClusterIssuer
      name: ${INTERNAL_CLUSTER_ISSUER}

api:
  image:
    repository: nginx
    pullPolicy: IfNotPresent
    tag: "1.27.0"
  serviceType: ClusterIP
  containerPort: 80
  servicePort: 80
  replicaCount: 2

web:
  image:
    repository: docker.io/tilowiklundsensmetry/resourcehealth_web
    pullPolicy: IfNotPresent
    tag: "v0.0.4"
  serviceType: ClusterIP
  containerPort: 3000
  servicePort: 80
  replicaCount: 2
  environmentSecrets:
    - name: OPENSEARCH_USERNAME
      secret: sensmetry-user-secret
      key: username
    - name: OPENSEARCH_PASSWORD
      secret: sensmetry-user-secret
      key: password
  environmentFixed:
    - name: OPENSEARCH_ENDPOINT
      value: "https://opensearch-cluster-master-headless.resource-health-opensearch.svc.cluster.local:9200"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: ${CLUSTER_ISSUER}
  host: resource-health.${INGRESS_HOST}
  tls:
    - secretName: resource-health.${INGRESS_HOST}-tls
      hosts:
        - resource-health.${INGRESS_HOST}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}