apiVersion: v1
kind: Secret
metadata:
  name: <client-name>-keycloak-client
  namespace: iam-management
stringData:
  client_secret: <client-secret>
---
apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: Client
metadata:
  name: <client-name>
  namespace: iam-management
spec:
  forProvider:
    realmId: ${REALM}
    clientId: <client-name>
    name: <Descriptive Client Name>
    description: <Description of the Client Purpose>
    enabled: true
    accessType: CONFIDENTIAL
    rootUrl: ${HTTP_SCHEME}://<service-name>.${INGRESS_HOST}
    baseUrl: ${HTTP_SCHEME}://<service-name>.${INGRESS_HOST}
    adminUrl: ${HTTP_SCHEME}://<service-name>.${INGRESS_HOST}
    serviceAccountsEnabled: true
    directAccessGrantsEnabled: true
    standardFlowEnabled: true
    oauth2DeviceAuthorizationGrantEnabled: true
    useRefreshTokens: true
    authorization:
      - allowRemoteResourceManagement: false
        decisionStrategy: UNANIMOUS
        keepDefaults: true
        policyEnforcementMode: ENFORCING
    validRedirectUris:
      - "${HTTP_SCHEME}://<service-name>.${INGRESS_HOST}/*"
    webOrigins:
      - "${HTTP_SCHEME}://<service-name>.${INGRESS_HOST}"
    clientSecretSecretRef:
      name: <client-name>-keycloak-client
      key: client_secret
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
