apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mlf
  namespace: sharinghub
  annotations:
    kubernetes.io/ingress.class: {{ getenv "INGRESS_CLASS" }}
    k8s.apisix.apache.org/rewrite-target-regex: "/mlflow/(.*)"
    k8s.apisix.apache.org/rewrite-target-regex-template: "/$1"
    {{- range $key, $value := (datasource "annotations") }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
spec:
  ingressClassName: {{ getenv "INGRESS_CLASS" }}
  {{- if eq ( getenv "HTTP_SCHEME" ) "https" }}
  tls:
    - hosts:
        - sharinghub.{{ getenv "INGRESS_HOST" }}
      secretName: sh-tls
  {{- end }}
  rules:
    - host: sharinghub.{{ getenv "INGRESS_HOST" }}
      http:
        paths:
          - path: "/mlflow"
            pathType: Prefix
            backend:
              service:
                name: mlflow-sharinghub
                port:
                  number: 5000
