apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mlf
  namespace: sharinghub
  annotations:
    kubernetes.io/ingress.class: {{ getenv "INGRESS_CLASS" }}

    {{- if eq (getenv "INGRESS_CLASS") "nginx" }}
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Script-Name /mlflow;
      rewrite ^/mlflow/(.*)$ /$1 break;

    {{- else if eq (getenv "INGRESS_CLASS") "apisix" }}
    k8s.apisix.apache.org/rewrite-target-regex: "/mlflow/(.*)"
    k8s.apisix.apache.org/rewrite-target-regex-template: "/$1"
    {{- end }}

    {{- range $key, $value := (datasource "annotations") }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
spec:
  ingressClassName: {{ getenv "INGRESS_CLASS" }}
  {{- if eq ( getenv "USE_CERT_MANAGER" ) "yes" }}
  tls:
    - hosts:
        - sharinghub.{{ getenv "INGRESS_HOST" }}
      secretName: sh-tls
  {{- end }}
  rules:
    {{- if eq ( getenv "PATH_BASED_ROUTING" ) "true" }}
    - host: {{ getenv "INGRESS_HOST" }}
    {{- else }}
    - host: sharinghub.{{ getenv "INGRESS_HOST" }}
    {{- end }}
      http:
        paths:
        {{- if eq (getenv "INGRESS_CLASS") "nginx" }}
          - path: /mlflow(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: mlflow-sharinghub
                port:
                  number: 5000
        {{- else if eq (getenv "INGRESS_CLASS") "apisix" }}
          - path: "/mlflow"
            pathType: Prefix
            backend:
              service:
                name: mlflow-sharinghub
                port:
                  number: 5000
        {{- end }}
