apiVersion: v1
kind: Service
metadata:
  name: mlflow-postgres
  namespace: sharinghub
  labels:
    app: mlflow-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: mlflow-postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-postgres-pvc
  namespace: sharinghub
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ getenv "PERSISTENT_STORAGECLASS" }}
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-postgres
  namespace: sharinghub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-postgres
  template:
    metadata:
      labels:
        app: mlflow-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_DB
          value: mlflow
        - name: POSTGRES_USER
          value: {{ getenv "MLFLOW_POSTGRES_USERNAME" }}
        - name: POSTGRES_PASSWORD
          value: "{{ getenv "MLFLOW_POSTGRES_PASSWORD" }}"
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - pg_isready -U {{ getenv "MLFLOW_POSTGRES_USERNAME" }} -d mlflow
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - pg_isready -U {{ getenv "MLFLOW_POSTGRES_USERNAME" }} -d mlflow
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: mlflow-postgres-pvc