image:
  repository: eoepca/mlflow-sharinghub
  pullPolicy: IfNotPresent

mlflowSharinghub:
  {{- if eq ( getenv "PATH_BASED_ROUTING" ) "true" }}
  sharinghubUrl: {{ getenv "HTTP_SCHEME" }}://{{ getenv "INGRESS_HOST" }}
  {{- else }}
  sharinghubUrl: {{ getenv "HTTP_SCHEME" }}://sharinghub.{{ getenv "INGRESS_HOST" }}

  {{- end }}
  sharinghubStacCollection: ai-model
  sharinghubAuthDefaultToken: false
  artifactsDestination: s3://{{ getenv "S3_BUCKET_MLFLOW" }}
  
  {{- if not (eq (getenv "GITLAB_URL") "") }}
  gitlabUrl: {{ getenv "GITLAB_URL" }}
  {{- end }}

persistence:
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  annotations:
    helm.sh/resource-policy: keep

podSecurityContext:
  fsGroup: 999

s3:
  enabled: true
  endpointUrl: {{ getenv "S3_ENDPOINT" }}

postgresql:
  enabled: true
  auth:
    existingSecret: mlflow-sharinghub-postgres
  global:
    storageClass: {{ getenv "STORAGE_CLASS" }}
  persistence:
    storageClass: {{ getenv "STORAGE_CLASS" }}
    size: 1Gi


ingress:
  enabled: false
