image:
  repository: eoepca/mlflow-sharinghub
  pullPolicy: IfNotPresent

mlflowSharinghub:
  sharinghubUrl: $HTTP_SCHEME://sharinghub.${INGRESS_HOST}
  sharinghubStacCollection: ai-model
  sharinghubAuthDefaultToken: false
  artifactsDestination: s3://${S3_BUCKET_MLFLOW}

s3:
  enabled: true
  endpointUrl: ${S3_ENDPOINT}

ingress:
  enabled: false
