identity-postgres:
  enabled: true
  namespaceOverride: "${IS_NAMESPACE_OVERRIDE}"
  persistence:
    storageClassName: "${DB_STORAGE_CLASS}"
  secrets:
    postgresPassword: "${IS_POSTGRES_PASSWORD}"
    pgPassword: "${IS_POSTGRES_PASSWORD}"
  volumeClaim:
    name: "${IS_VOLUME_CLAIM_NAME}"
    create: "${IS_CREATE_VOLUME_CLAIM}"

identity-keycloak:
  enabled: true
  namespaceOverride: "${IS_NAMESPACE_OVERRIDE}"
  secrets:
    keycloakAdminPassword: "${IS_KEYCLOAK_ADMIN_PASSWORD}"
    kcDbPassword: "${IS_KEYCLOAK_DB_PASSWORD}"
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: ${CLUSTER_ISSUER}
    hosts:
      - host: identity.keycloak.${INGRESS_HOST}
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: identity-keycloak-tls-certificate
        hosts:
          - identity.keycloak.${INGRESS_HOST}

identity-api:
  enabled: true
  namespaceOverride: "${IS_NAMESPACE_OVERRIDE}"
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: ${CLUSTER_ISSUER}
    hosts:
      - host: identity.api.${INGRESS_HOST}
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: identity-api-tls-certificate
        hosts:
          - identity.api.${INGRESS_HOST}
  secrets:
    optional: false
    adminPassword: "${IS_API_ADMIN_PASSWORD}"

identity-api-gatekeeper:
  enabled: true
  config:
    client-id: identity-api
    discovery-url: https://identity.keycloak.${INGRESS_HOST}/realms/master
    cookie-domain: ${INGRESS_HOST}
  targetService:
    host: identity-api-protected.${INGRESS_HOST}
    name: identity-api
    port:
      number: 8080
  secrets:
    clientSecret: "${IS_API_GATEKEEPER_CLIENT_SECRET}"
    encryptionKey: "${IS_API_GATEKEEPER_ENCRYPTION_KEY}"
  ingress:
    enabled: true
    className: nginx
    annotations:
      ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    openUri:
      - ^/(docs|openapi.json)
    hosts:
      - host: identity.api.${INGRESS_HOST}
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: identity-api-tls-certificate
        hosts:
          - identity.api.${INGRESS_HOST}