identity-postgres:
  enabled: true
  secrets:
    postgresPassword: "${IS_POSTGRES_PASSWORD}"
    pgPassword: "${IS_POSTGRES_PASSWORD}"
  volumeClaim:
    name: identity-service

identity-keycloak:
  enabled: true
  secrets:
    keycloakAdminPassword: "${IS_KEYCLOAK_ADMIN_PASSWORD}"
    kcDbPassword: "${IS_POSTGRES_PASSWORD}"
  ingress:
    enabled: true
    className: nginx
    annotations:
      ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/cluster-issuer: ${CLUSTER_ISSUER}
    hosts:
      - host: identity.keycloak.${INGRESS_HOST}
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: identity-keycloak-tls-certificate
        hosts:
          - identity.keycloak.${INGRESS_HOST}

identity-api:
  enabled: true
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: ${CLUSTER_ISSUER}
    hosts:
      - host: identity.api.${INGRESS_HOST}
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: identity-api-tls-certificate
        hosts:
          - identity.api.${INGRESS_HOST}
  secrets:
    optional: false
    adminPassword: "${IS_KEYCLOAK_ADMIN_PASSWORD}"
  deployment:
    extraEnv:
      - name: AUTH_SERVER_URL
        value: $HTTP_SCHEME://identity.keycloak.${INGRESS_HOST}
      - name: ADMIN_USERNAME
        value: "admin"
      - name: REALM
        value: "master"
      - name: LOG_LEVEL
        value: DEBUG
  
# identity-api-gatekeeper:
#   enabled: false

identity-api-gatekeeper:
  enabled: false