apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: Client
metadata:
  name: openeo-argo
  namespace: iam-management
spec:
  forProvider:
    realmId: {{ getenv "REALM" }}
    clientId: openeo-argo
    name: openEO Argo Engine
    description: openEO Argo Engine OIDC
    enabled: true
    accessType: PUBLIC
    rootUrl: {{ getenv "HTTP_SCHEME" }}://openeo.{{ getenv "INGRESS_HOST" }}
    baseUrl: {{ getenv "HTTP_SCHEME" }}://openeo.{{ getenv "INGRESS_HOST" }}
    adminUrl: {{ getenv "HTTP_SCHEME" }}://openeo.{{ getenv "INGRESS_HOST" }}
    directAccessGrantsEnabled: true
    standardFlowEnabled: true
    oauth2DeviceAuthorizationGrantEnabled: true
    useRefreshTokens: true
    validRedirectUris:
      - "/*"
      - "https://editor.openeo.org/*"
    webOrigins:
      - "+"
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
---
apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: ClientDefaultScopes
metadata:
  name: openeo-argo-default-scopes
  namespace: iam-management
spec:
  providerConfigRef:
    name: keycloak-provider-config
    kind: ProviderConfig
  forProvider:
    realmId: {{ getenv "REALM" }}
    clientIdRef:
      name: openeo-argo
      policy:
        resolution: Required
    defaultScopes:
      - profile
      - email
      - basic
