---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: keycloak
spec:
  http:
    - name: keycloak
      backends:
        - serviceName: keycloak
          servicePort: 80
      match:
        hosts:
          - auth.{{ getenv "INGRESS_HOST" }}
        paths:
          - /*
      plugins:
        # Allow CORS access
        - name: cors
          enable: true
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth
spec:
  dnsNames:
    - auth.{{ getenv "INGRESS_HOST" }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ getenv "CLUSTER_ISSUER" }}
  secretName: auth-tls
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: keycloak
spec:
  hosts:
    - auth.{{ getenv "INGRESS_HOST" }}
  secret:
    name: auth-tls
    namespace: iam
