---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: keycloak
spec:
  http:
    - name: keycloak
      backends:
        - serviceName: keycloak
          servicePort: 80
      match:
        hosts:
          - auth-apx.$INGRESS_HOST
        paths:
          - /*
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-apx
spec:
  dnsNames:
    - auth-apx.$INGRESS_HOST
  issuerRef:
    kind: ClusterIssuer
    name: ${CLUSTER_ISSUER}
  secretName: auth-apx-tls
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: keycloak
spec:
  hosts:
    - auth-apx.$INGRESS_HOST
  secret:
    name: auth-apx-tls
    namespace: iam
