apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  namespace: iam
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    {{- range $key, $value := (datasource "annotations") }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - auth.{{ getenv "INGRESS_HOST" }}
      secretName: auth-tls
  rules:
    - host: auth.{{ getenv "INGRESS_HOST" }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 80
