global:
  storageClass: $STORAGE_CLASS

# Uncomment and modify the image section if using a custom Keycloak image with OPA plugin
# image:
#   registry: byud8gih.c1.de1.container-registry.ovh.net
#   repository: eoepca/keycloak-with-opa-plugin
#   tag: 0.3.1
  # pullPolicy: Always
auth:
  adminUser: $KEYCLOAK_ADMIN_USER
  existingSecret: keycloak-admin
proxy: edge
extraEnvVars:
  - name: KC_SPI_POLICY_OPA_OPA_BASE_URI
    value: "http://opa-opal-client:8181/v1/data/"
  - name: KC_SPI_POLICY_OPA_OPA_POLICY_DIR
    value: "/opt/bitnami/keycloak/conf/opa-policies"
  - name: KC_HOSTNAME_URL
    value: "https://auth.$INGRESS_HOST"
  - name: KC_HOSTNAME_ADMIN_URL
    value: "https://auth.$INGRESS_HOST"
postgresql:
  auth:
    existingSecret: kc-postgres

# Resources
#
# Either using a preset
resourcesPreset: "large"
#
# Or for a small (resource limited) deployment
# resources:
#   requests:
#     cpu: 200m
#     memory: 2048Mi
