apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: application-hub
  namespace: app-hub
  annotations:
    kubernetes.io/ingress.class: {{ getenv "INGRESS_CLASS" }}
    {{- range $key, $value := (datasource "annotations") }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
    {{- if eq ( getenv "INGRESS_CLASS" ) "apisix" }}
    k8s.apisix.apache.org/enable-websocket: "true"
    {{- else if eq ( getenv "INGRESS_CLASS" ) "nginx" }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    {{- end }}
spec:
  ingressClassName: {{ getenv "INGRESS_CLASS" }}
  rules:
    - host: {{ getenv "APPHUB_PUBLIC_HOST" }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: application-hub-proxy-public
                port:
                  number: 80
  {{- if eq ( getenv "HTTP_SCHEME" ) "https" }}
  tls:
    - hosts:
        - {{ getenv "APPHUB_PUBLIC_HOST" }}
      secretName: app-hub-tls
  {{- end }}
