apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ah
  namespace: application-hub
  annotations:
    kubernetes.io/ingress.class: apisix
    ${CLUSTER_ISSUER_ANNOTATION}
    k8s.apisix.apache.org/enable-websocket: "true"
spec:
  ingressClassName: apisix
  rules:
    - host: app-hub.$INGRESS_HOST
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: application-hub-proxy-public
                port:
                  number: 80
  tls:
    - hosts:
        - app-hub.$INGRESS_HOST
      secretName: app-hub-tls
