apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ah
  namespace: application-hub
  annotations:
    kubernetes.io/ingress.class: {{ getenv "INGRESS_CLASS" }}
    {{- range $key, $value := (datasource "annotations") }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
    k8s.apisix.apache.org/enable-websocket: "true"
spec:
  ingressClassName: {{ getenv "INGRESS_CLASS" }}
  rules:
    - host: app-hub.{{ getenv "INGRESS_HOST" }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: application-hub-proxy-public
                port:
                  number: 80
  tls:
    - hosts:
        - app-hub.{{ getenv "INGRESS_HOST" }}
      secretName: app-hub-tls
