ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: app-hub.${INGRESS_HOST}
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: app-hub-tls
      hosts:
      - app-hub.${INGRESS_HOST}
  clusterIssuer: ${CLUSTER_ISSUER}

jupyterhub:
  fullnameOverride: "application-hub"
  hub:
    extraEnv:
      JUPYTERHUB_ENV: "dev"
      JUPYTERHUB_SINGLE_USER_IMAGE: "eoepca/pde-container:1.0.3"
      APP_HUB_NAMESPACE: "default"
      STORAGE_CLASS: ${STORAGE_CLASS}
      RESOURCE_MANAGER_WORKSPACE_PREFIX: "ws"

      JUPYTERHUB_CRYPT_KEY: "${APPHUB_JUPYTERHUB_CRYPT_KEY}"
      OAUTH_CALLBACK_URL: $HTTP_SCHEME://app-hub.${INGRESS_HOST}/hub/oauth_callback
      OAUTH_LOGOUT_REDIRECT_URL: $HTTP_SCHEME://app-hub.${INGRESS_HOST}/hub/home
      OAUTH2_USERDATA_URL: $HTTP_SCHEME://identity.keycloak.${INGRESS_HOST}/realms/master/protocol/openid-connect/userinfo
      OAUTH2_TOKEN_URL: $HTTP_SCHEME://identity.keycloak.${INGRESS_HOST}/realms/master/protocol/openid-connect/token
      OAUTH2_AUTHORIZE_URL: $HTTP_SCHEME://identity.keycloak.${INGRESS_HOST}/realms/master/protocol/openid-connect/auth
      OAUTH_CLIENT_ID: application-hub
      OAUTH_CLIENT_SECRET: "${APPHUB_CLIENT_SECRET}"

    image:
      pullPolicy: Always

    db:
      pvc:
        storageClassName: ${STORAGE_CLASS}

  singleuser:
    image:
      name: jupyter/minimal-notebook
      tag: "2343e33dec46"
    profileList: 
    - display_name:  "Minimal environment"
      description: "To avoid too much bells and whistles: Python."
      default: "True"
    - display_name:  "EOEPCA profile"
      description: "Sample profile"
      kubespawner_override:
        cpu_limit: 4
        mem_limit: "8G"
nodeSelector:
  key: "node-role.kubernetes.io/worker"
  value: "true"