---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: zoo-api
  namespace: processing
spec:
  ingressClassName: apisix
  http:
    # Open access to ZOO OpenAPI docs and conformance metadata only.
    - name: zoo-docs
      match:
        hosts:
          - zoo.{{ getenv "INGRESS_HOST" }}
        paths:
          - /ogc-api
          - /ogc-api/
          - /ogc-api/api*
          - /swagger-ui*
          - /ogc-api/conformance*
      backends:
        - serviceName: zoo-project-dru-service
          servicePort: 80
      plugins:
        - name: cors
          enable: true

    # Protected access to OAPIP operations.
    - name: zoo-protected
      match:
        hosts:
          - zoo.{{ getenv "INGRESS_HOST" }}
        paths:
          - /*
      backends:
        - serviceName: zoo-project-dru-service
          servicePort: 80
      plugins:
        - name: openid-connect
          enable: true
          config:
            discovery: "{{ getenv "HTTP_SCHEME" }}://{{ getenv "KEYCLOAK_HOST" }}/realms/{{ getenv "REALM" }}/.well-known/openid-configuration"
            realm: "{{ getenv "REALM" }}"
            client_id: "{{ getenv "OAPIP_CLIENT_ID" }}"
            client_secret: "{{ getenv "OAPIP_CLIENT_SECRET" }}"
            session:
              secret: "{{ getenv "OAPIP_CLIENT_SECRET" }}"
            use_jwks: true
            bearer_only: false
            set_access_token_header: true
            access_token_in_authorization_header: true
        - name: authz-keycloak
          enable: true
          config:
            discovery: "{{ getenv "HTTP_SCHEME" }}://{{ getenv "KEYCLOAK_HOST" }}/realms/{{ getenv "REALM" }}/.well-known/uma2-configuration"
            lazy_load_paths: true
            ssl_verify: false
            client_id: "{{ getenv "OAPIP_CLIENT_ID" }}"
            client_secret: "{{ getenv "OAPIP_CLIENT_SECRET" }}"
        - name: cors
          enable: true
{{- if eq ( getenv "HTTP_SCHEME" ) "https" }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zoo
  namespace: processing
spec:
  dnsNames:
    - zoo.{{ getenv "INGRESS_HOST" }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ getenv "CLUSTER_ISSUER" }}
  secretName: zoo-tls
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: zoo
  namespace: processing
spec:
  ingressClassName: apisix
  hosts:
    - zoo.{{ getenv "INGRESS_HOST" }}
  secret:
    name: zoo-tls
    namespace: processing
{{- end }}