---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: zoo-api
spec:
  http:
    # Open access to zoo OpenAPI docs
    - name: zoo-docs
      match:
        hosts:
          - zoo-apx.$INGRESS_HOST
        paths:
          - /*
        exprs:
          - subject:
              scope: Path
            op: RegexMatch
            value: "^/(ogc-api/api.*|swagger-ui.*)"
      backends:
        - serviceName: zoo-project-dru-service
          servicePort: 80
      plugins:
        # Allow CORS access
        - name: cors
          enable: true

    # Authorized access to zoo API
    - name: zoo-protected
      match:
        hosts:
          - zoo-apx.$INGRESS_HOST
        paths:
          - /*
      backends:
        - serviceName: zoo-project-dru-service
          servicePort: 80
      plugins:
        # Authenticate - expect JWT in `Authorization: Bearer` header
        - name: openid-connect
          enable: true
          config:
            discovery: "https://auth-apx.$INGRESS_HOST/realms/eoepca/.well-known/openid-configuration"
            realm: eoepca
            bearer_only: true
          secretRef: oapip-engine-client
        # Authorization - required for access to API
        - name: authz-keycloak
          enable: true
          config:
            discovery: "https://auth-apx.$INGRESS_HOST/realms/eoepca/.well-known/uma2-configuration"
            lazy_load_paths: true
            ssl_verify: false
          secretRef: oapip-engine-client
        # Allow CORS access
        - name: cors
          enable: true
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zoo-apx
spec:
  dnsNames:
    - zoo-apx.$INGRESS_HOST
  issuerRef:
    kind: ClusterIssuer
    name: ${CLUSTER_ISSUER}-apx
  secretName: zoo-apx-tls
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: zoo-apx
spec:
  hosts:
    - zoo-apx.$INGRESS_HOST
  secret:
    name: zoo-apx-tls
    namespace: processing
