apiVersion: apps/v1
kind: Deployment
metadata:
  name: eodata-server
  namespace: resource-registration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eodata-server
  template:
    metadata:
      labels:
        app: eodata-server
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80
        volumeMounts:
        - name: eodata
          mountPath: /usr/share/nginx/html
      volumes:
      - name: eodata
        persistentVolumeClaim:
          claimName: eodata
---
apiVersion: v1
kind: Service
metadata:
  name: eodata-server
  namespace: resource-registration
spec:
  selector:
    app: eodata-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eodata-server
  namespace: resource-registration
  annotations:
    {{- range $key, $value := (datasource "annotations") }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
{{- if eq (getenv "INGRESS_CLASS") "apisix" }}
    k8s.apisix.apache.org/enable-websocket: "true"
{{- end }}
spec:
  ingressClassName: {{ getenv "INGRESS_CLASS" }}
  rules:
    - host: eodata.{{ getenv "INGRESS_HOST" }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eodata-server
                port:
                  number: 80
  {{- if eq ( getenv "HTTP_SCHEME" ) "https" }}
  tls:
    - hosts:
        - eodata.{{ getenv "INGRESS_HOST" }}
      secretName: eodata-server-tls
  {{- end }}
