{{- if eq (getenv "INGRESS_CLASS") "apisix" }}
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: registration-harvester-bpm-engine
  namespace: resource-registration
spec:
  ingressClassName: apisix
  http:
    - name: redirect-root
      match:
        hosts:
          - registration-harvester-bpm-engine.{{ getenv "INGRESS_HOST" }}
        paths:
          - /
          - /operaton
      plugins:
        - name: redirect
          enable: true
          config:
            uri: /operaton/
      backends:
        - serviceName: registration-harvester-bpm-engine-operaton
          servicePort: 8080

    - name: rewrite-operaton-path
      match:
        hosts:
          - registration-harvester-bpm-engine.{{ getenv "INGRESS_HOST" }}
        paths:
          - /operaton/*
      backends:
        - serviceName: registration-harvester-bpm-engine-operaton
          servicePort: 8080

    - name: redirect-rest-api
      match:
        hosts:
          - registration-harvester-bpm-engine.{{ getenv "INGRESS_HOST" }}
        paths:
          - /engine-rest
      plugins:
        - name: redirect
          enable: true
          config:
            uri: /engine-rest/
      backends:
        - serviceName: registration-harvester-bpm-engine-operaton
          servicePort: 8080

    - name: rewrite-operaton-rest-api-path
      match:
        hosts:
          - registration-harvester-bpm-engine.{{ getenv "INGRESS_HOST" }}
        paths:
          - /engine-rest/*
      backends:
        - serviceName: registration-harvester-bpm-engine-operaton
          servicePort: 8080
{{- if eq ( getenv "HTTP_SCHEME" ) "https" }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registration-harvester-bpm-engine-tls
  namespace: resource-registration
spec:
  dnsNames:
    - registration-harvester-bpm-engine.{{ getenv "INGRESS_HOST" }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ getenv "CLUSTER_ISSUER" }}
  secretName: registration-harvester-bpm-engine-tls
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: registration-harvester-bpm-engine-tls
  namespace: resource-registration
spec:
  ingressClassName: apisix
  hosts:
    - registration-harvester-bpm-engine.{{ getenv "INGRESS_HOST" }}
  secret:
    name: registration-harvester-bpm-engine-tls
    namespace: resource-registration
{{- end }}

{{- else }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registration-harvester-bpm-engine
  namespace: resource-registration
  annotations:
    {{- range $key, $value := (datasource "annotations") }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
    nginx.ingress.kubernetes.io/app-root: /operaton/
spec:
  ingressClassName: {{ getenv "INGRESS_CLASS" }}
  rules:
    - host: registration-harvester-bpm-engine.{{ getenv "INGRESS_HOST" }}
      http:
        paths:
          - path: /operaton
            pathType: Prefix
            backend:
              service:
                name: registration-harvester-bpm-engine-operaton
                port:
                  number: 8080
          - path: /engine-rest
            pathType: Prefix
            backend:
              service:
                name: registration-harvester-bpm-engine-operaton
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: registration-harvester-bpm-engine-operaton
                port:
                  number: 8080
  {{- if eq ( getenv "HTTP_SCHEME" ) "https" }}
  tls:
    - hosts:
        - registration-harvester-bpm-engine.{{ getenv "INGRESS_HOST" }}
      secretName: registration-harvester-bpm-engine-tls
  {{- end }}
{{- end }}
