apiVersion: apps/v1
kind: Deployment
metadata:
  name: stac-browser
  namespace: resource-registration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stac-browser
  template:
    metadata:
      labels:
        app: stac-browser
    spec:
      containers:
        - name: stac-browser
          image: ghcr.io/radiantearth/stac-browser:latest
          ports:
            - containerPort: 8080
          env:
            - name: SB_catalogUrl
              value: "{{ getenv "HTTP_SCHEME" }}://resource-catalogue.{{ getenv "INGRESS_HOST" }}/stac"
            - name: SB_catalogTitle
              value: "EOEPCA Catalogue"
---
apiVersion: v1
kind: Service
metadata:
  name: stac-browser
  namespace: resource-registration
spec:
  selector:
    app: stac-browser
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stac-browser
  namespace: resource-registration
  annotations:
    {{- range $key, $value := (datasource "annotations") }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
    k8s.apisix.apache.org/enable-websocket: "true"
spec:
  ingressClassName: {{ getenv "INGRESS_CLASS" }}
  rules:
    - host: stac-browser.{{ getenv "INGRESS_HOST" }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stac-browser
                port:
                  number: 8080
  {{- if eq ( getenv "HTTP_SCHEME" ) "https" }}
  tls:
    - hosts:
        - stac-browser.{{ getenv "INGRESS_HOST" }}
      secretName: stac-browser-tls
  {{- end }}
