apiVersion: v1
kind: Secret
metadata:
  name: resource-catalogue-db-secret
  namespace: resource-discovery
type: Opaque
stringData:
  username: pycsw
  password: {{ getenv "RESOURCE_DISCOVERY_DB_PASSWORD" }}
