apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resource-catalogue
  namespace: resource-discovery
  annotations:
    {{- range $key, $value := (datasource "annotations") }}
    {{ $key }}: "{{ $value }}"
    {{- end }}

spec:
  ingressClassName: {{ getenv "INGRESS_CLASS" }}
  rules:
    - host: resource-catalogue.{{ getenv "INGRESS_HOST" }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: resource-catalogue-service
                port:
                  number: 80
  {{- if eq ( getenv "HTTP_SCHEME" ) "https" }}
  tls:
    - hosts:
        - resource-catalogue.{{ getenv "INGRESS_HOST" }}
      secretName: resource-catalogue-tls
  {{- end }}
