apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rc
  namespace: resource-discovery
  annotations:
    kubernetes.io/ingress.class: ${INGRESS_CLASS}
${CUSTOM_INGRESS_ANNOTATIONS}
spec:
  ingressClassName: ${INGRESS_CLASS}
  rules:
    - host: resource-catalogue.$INGRESS_HOST
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: resource-catalogue-service
                port:
                  number: 80
  tls:
    - hosts:
        - resource-catalogue.$INGRESS_HOST
      secretName: resource-catalogue-tls
