global:
  namespace: resource-discovery
ingress:
  enabled: false
db:
  volume_storageclass: {{ getenv "PERSISTENT_STORAGECLASS" }}
  volume_access_modes: ReadWriteOnce
pycsw:
  config:
    server:
      url: {{ getenv "HTTP_SCHEME" }}://resource-catalogue.{{ getenv "INGRESS_HOST" }}
    manager:
      transactions: "true"
      allowed_ips:
        - '"*"'
    metadata:
      identification:
        title: EOEPCA+ Resource Catalogue
        description: EOEPCA+ Resource Catalogue
        keywords:
            - EOEPCA+
            - Earth observation
            - discovery
        license:
          name: CC-BY 4.0 license
          url: https://creativecommons.org/licenses/by/4.0
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0
        url: https://eoepca.org
      provider:
        name: EOEPCA+
        url: https://eoepca.org/
    repository:
      facets:
          - type