global:
  namespace: resource-discovery
ingress:
  enabled: false
db:
  volume_storage_type: {{ getenv "STORAGE_CLASS" }}
pycsw:
  config:
    server:
      url: {{ getenv "HTTP_SCHEME" }}://resource-catalogue.{{ getenv "INGRESS_HOST" }}
    manager:
      transactions: "true"
      allowed_ips:
        - '"*"'
    metadata:
      identification:
        title: EOEPCA Resource Catalogue
        description: pycsw is an OARec and OGC CSW server implementation written in Python
      provider:
        name: EOEPCA
        url: https://eoepca.org/
