apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: datacube-access
  namespace: datacube-access
  annotations:
    {{- range $key, $value := (datasource "annotations") }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
spec:
  ingressClassName: {{ getenv "INGRESS_CLASS" }}
  rules:
    - host: datacube-access.{{ getenv "INGRESS_HOST" }}
      http:
        paths:
          - path: "/"
            pathType: ImplementationSpecific
            backend:
              service:
                name: datacube-access
                port:
                  number: 8000
  tls:
    - hosts:
        - datacube-access.{{ getenv "INGRESS_HOST" }}
      secretName: datacube-access-tls