configMaps:
  conf: |
    from openeo_aggregator.config import AggregatorBackendConfig
    from openeo_driver.users.oidc import OidcProvider

    oidc_providers = [
        OidcProvider(
            id="egi",
            title="EGI Check-in",
            issuer="https://aai.egi.eu/auth/realms/egi/",
            scopes=["openid", "email"],
            default_clients=[
                {
                    "id": "vito-default-client",
                    "grant_types": [
                        "authorization_code+pkce",
                        "urn:ietf:params:oauth:grant-type:device_code+pkce",
                        "refresh_token",
                    ],
                    "redirect_urls": ["https://editor.openeo.org"],
                }
            ],
        ),
        OidcProvider(
            id="egi-dev",
            title="EGI Check-in (dev)",
            issuer="https://aai-dev.egi.eu/auth/realms/egi/",
            scopes=["openid", "email"],
            default_clients=[
                {
                    "id": "openeo-eoepca-demo",
                    "grant_types": [
                        "authorization_code+pkce",
                        "urn:ietf:params:oauth:grant-type:device_code+pkce",
                        "refresh_token",
                    ],
                    "redirect_urls": ["https://editor.openeo.org"],
                }
            ],
        ),
    ]

    config = AggregatorBackendConfig(
        id="openeo-eoepca-aggregator-demo",
        capabilities_title="openEO/EOEPCA+ Federation Demo",
        capabilities_description="openEO demo federation service for EOEPCA+",
        oidc_providers=oidc_providers,
        aggregator_backends={
            "terrascope": "https://openeo-dev.vito.be/openeo/1.2/",
            "eoepca": "https://openeo.${INGRESS_HOST}/openeo/1.2/",
        },
    )

envVars:
  ENV: "prod"
  ZOOKEEPERNODES: openeo-geotrellis-zookeeper.openeo-geotrellis.svc.cluster.local:2181
  GUNICORN_CMD_ARGS: "--bind=0.0.0.0:8080 --workers=10 --threads=1 --timeout=900"
existingConfigMaps: false
fullnameOverride: openeofed
image:
  pullPolicy: Always
  repository: vito-docker.artifactory.vgt.vito.be/openeo-aggregator
  tag: latest
replicaCount: 1
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: apisix
    cert-manager.io/cluster-issuer: ${CLUSTER_ISSUER}
    k8s.apisix.apache.org/enable-cors: "true"
    k8s.apisix.apache.org/http-to-https: "true"
  hosts:
    - host: openeofed.${INGRESS_HOST}
      paths:
        - path: /.well-known/openeo
          pathType: Prefix
        - path: /openeo
          pathType: Prefix
  tls:
    - secretName: openeofed-cert
      hosts:
        - openeofed.${INGRESS_HOST}