apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-cert
  namespace: iam
spec:
  secretName: auth-cert-tls
  issuerRef:
    kind: ClusterIssuer
    name: {{ getenv "CLUSTER_ISSUER" }}
  dnsNames:
  - auth.{{ getenv "INGRESS_HOST" }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: identity-api-cert
  namespace: iam
spec:
  secretName: identity-api-cert-tls
  issuerRef:
    kind: ClusterIssuer
    name: {{ getenv "CLUSTER_ISSUER" }}
  dnsNames:
  - identity-api.{{ getenv "INGRESS_HOST" }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opa-cert
  namespace: iam
spec:
  secretName: opa-cert-tls
  issuerRef:
    kind: ClusterIssuer
    name: {{ getenv "CLUSTER_ISSUER" }}
  dnsNames:
  - opa.{{ getenv "INGRESS_HOST" }}
---
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: auth-apisix-tls
  namespace: iam
spec:
  hosts:
    - auth.{{ getenv "INGRESS_HOST" }}
  secret:
    name: auth-cert-tls
    namespace: iam
---
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: identity-api-apisix-tls
  namespace: iam
spec:
  hosts:
    - identity-api.{{ getenv "INGRESS_HOST" }}
  secret:
    name: identity-api-cert-tls
    namespace: iam
---
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: opa-apisix-tls
  namespace: iam
spec:
  hosts:
    - opa.{{ getenv "INGRESS_HOST" }}
  secret:
    name: opa-cert-tls
    namespace: iam