#!/usr/bin/env bash

ORIG_DIR="$(pwd)"
cd "$(dirname "$0")"
BIN_DIR="$(pwd)"

onExit() {
  cd "${ORIG_DIR}"
}
trap onExit EXIT

main() {
  rm -f ../eoepca/client.yaml
  sudo rm -rf /tmp/hostpath-provisioner
}

main "$@"
