apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
---
apiVersion: v1
kind: Namespace
metadata:
  name: knative-eventing
---
apiVersion: v1
kind: Namespace
metadata:
  name: notifications
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  version: "1.19"
  ingress:
    kourier:
      enabled: true
  config:
    domain:
      notifications.{{ getenv "INGRESS_HOST" }}: ""
    network:
      ingress-class: "kourier.ingress.networking.knative.dev"
    autoscaler:
      container-concurrency-target-default: "100"
      enable-scale-to-zero: "true"
      scale-to-zero-grace-period: "30s"
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
spec:
  version: "1.19"
  config:
    config-features:
      delivery-retryafter: "enabled"
      delivery-timeout: "enabled"
{{- if eq ( getenv "NA_ENABLE_OIDC" ) "yes" }}
      authentication-oidc: "enabled"
{{- end }}
  deployments:
    - name: eventing-webhook
      resources:
        - container: eventing-webhook
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 500Mi