serving:
  install: false
eventing:
  install: false
{{- if eq ( getenv "NA_ENABLE_OIDC" ) "yes" }}
  authenticationOidc: true
{{- else }}
  authenticationOidc: false
{{- end }}

apiServerSource:
  enabled: true

webhookSource:
  enabled: true
  secrets:
    create: true
    githubSecret: "{{ getenv "NA_GITHUB_WEBHOOK_SECRET" }}"
  sinkBinding:
    create: true
  ingress:
    enabled: true
    className: {{ getenv "INGRESS_CLASS" }}
    annotations:
      {{- range $key, $value := (datasource "annotations") }}
      {{ $key }}: "{{ $value }}"
      {{- end }}
    hosts:
      - host: webhooks.notifications.{{ getenv "INGRESS_HOST" }}
        paths:
          - path: /
            pathType: Prefix
{{- if eq ( getenv "HTTP_SCHEME" ) "https" }}
    tls:
      - hosts:
          - webhooks.notifications.{{ getenv "INGRESS_HOST" }}
        secretName: notification-automation-webhook-source-tls
{{- end }}

cloudEventsPlayer:
  enabled: true
  subscribeBroker:
    enabled: true
  ingress:
    enabled: true
    className: {{ getenv "INGRESS_CLASS" }}
    annotations:
      {{- range $key, $value := (datasource "annotations") }}
      {{ $key }}: "{{ $value }}"
      {{- end }}
      k8s.apisix.apache.org/enable-websocket: "true"
    hosts:
      - host: cloudevents-player.notifications.{{ getenv "INGRESS_HOST" }}
        paths:
          - path: /
            pathType: Prefix
{{- if eq ( getenv "HTTP_SCHEME" ) "https" }}
    tls:
      - hosts:
          - cloudevents-player.notifications.{{ getenv "INGRESS_HOST" }}
        secretName: notification-automation-cloudevents-player-tls
{{- end }}

emailer:
{{- if eq ( getenv "NA_ENABLE_EMAILER" ) "yes" }}
  install: true
  config:
    emailFrom: "{{ getenv "NA_EMAIL_FROM" }}"
    emailTo: "{{ getenv "NA_EMAIL_TO" }}"
    yagmailHost: "{{ getenv "NA_SMTP_HOST" }}"
    yagmailPort: "{{ getenv "NA_SMTP_PORT" }}"
    yagmailUser: "{{ getenv "NA_SMTP_USER" }}"
    yagmailPassword: "{{ getenv "NA_SMTP_PASSWORD" }}"
    yagmailSmtpStarttls: "{{ getenv "NA_SMTP_STARTTLS" }}"
{{- else }}
  install: false
{{- end }}
