cwlVersion: v1.0
class: CommandLineTool
id: stage-out
doc: "Stage-out the results to S3"
inputs:
  process:
    type: string
  collection_id:
    type: string
  STAGEOUT_OUTPUT:
    type: string
  STAGEOUT_AWS_ACCESS_KEY_ID:
    type: string
  STAGEOUT_AWS_SECRET_ACCESS_KEY:
    type: string
  STAGEOUT_AWS_REGION:
    type: string
  STAGEOUT_AWS_SERVICEURL:
    type: string
outputs:
  StacCatalogUri:
    outputBinding:
      outputEval: ${  return "s3://" + inputs.STAGEOUT_OUTPUT + "/" + inputs.process + "/catalog.json"; }
    type: string
baseCommand:
  - python
  - stageout.py
arguments:
  - $( inputs.wf_outputs.path )
  - $( inputs.STAGEOUT_OUTPUT )
  - $( inputs.process )
  - $( inputs.collection_id )
requirements:
  DockerRequirement:
    dockerPull: ghcr.io/terradue/ogc-eo-application-package-hands-on/stage:1.3.2
  InlineJavascriptRequirement: {}
  EnvVarRequirement:
    envDef:
      AWS_ACCESS_KEY_ID: $( inputs.STAGEOUT_AWS_ACCESS_KEY_ID )
      AWS_SECRET_ACCESS_KEY: $( inputs.STAGEOUT_AWS_SECRET_ACCESS_KEY )
      AWS_REGION: $( inputs.STAGEOUT_AWS_REGION )
      AWS_S3_ENDPOINT: $( inputs.STAGEOUT_AWS_SERVICEURL )
  InitialWorkDirRequirement:
    listing:
      - entryname: stageout.py
        entry: |-