apiVersion: apisix.apache.org/v2
kind: ApisixPluginConfig
metadata:
  name: resource-health-route-browser-auth-plugin
  namespace: resource-health
spec:
  plugins:
    - name: openid-connect
      enable: true
      config:
        set_id_token_header: true
        set_refresh_token_header: true
        discovery: "{{ getenv "HTTP_SCHEME" }}://{{ getenv "KEYCLOAK_HOST" }}/realms/{{ getenv "REALM" }}/.well-known/openid-configuration"
        scope: openid email profile offline_access
        # Following settings to enable support for both interactive and API access
        use_jwks: true                              # (default: false)
        bearer_only: false                          # (default: false)
        set_access_token_header: true               # (default: true)
        access_token_in_authorization_header: true  # (default: false)
      secretRef: resource-health-iam-client-credentials