---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eoapi-raster
  namespace: data-access
  annotations:
    k8s.apisix.apache.org/enable-cors: "true"
    k8s.apisix.apache.org/http-to-https: "true"
    k8s.apisix.apache.org/use-regex: "true"
    k8s.apisix.apache.org/rewrite-target-regex: "/raster(/|$)(.*)"
    k8s.apisix.apache.org/rewrite-target-regex-template: "/$2"
spec:
  ingressClassName: {{ getenv "INGRESS_CLASS" }}
  rules:
  - host: eoapi.{{ getenv "INGRESS_HOST" }}
    http:
      paths:
      - path: /raster(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: raster
            port:
              number: 8080
  {{- if eq ( getenv "HTTP_SCHEME" ) "https" }}
  tls:
  - hosts:
    - eoapi.{{ getenv "INGRESS_HOST" }}
    secretName: eoapi-tls
  {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eoapi-stac
  namespace: data-access
  annotations:
    {{- range $key, $value := (datasource "annotations") }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
    k8s.apisix.apache.org/enable-cors: "true"
    k8s.apisix.apache.org/http-to-https: "true"
    k8s.apisix.apache.org/use-regex: "true"
    k8s.apisix.apache.org/rewrite-target-regex: "/stac(/|$)(.*)"
    k8s.apisix.apache.org/rewrite-target-regex-template: "/$2"
spec:
  ingressClassName: {{ getenv "INGRESS_CLASS" }}
  rules:
  - host: eoapi.{{ getenv "INGRESS_HOST" }}
    http:
      paths:
      - path: /stac(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: stac
            port:
              number: 8080
  {{- if eq ( getenv "HTTP_SCHEME" ) "https" }}
  tls:
  - hosts:
    - eoapi.{{ getenv "INGRESS_HOST" }}
    secretName: eoapi-tls
  {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eoapi-vector
  namespace: data-access
  annotations:
    {{- range $key, $value := (datasource "annotations") }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
    k8s.apisix.apache.org/enable-cors: "true"
    k8s.apisix.apache.org/http-to-https: "true"
    k8s.apisix.apache.org/use-regex: "true"
    k8s.apisix.apache.org/rewrite-target-regex: "/vector(/|$)(.*)"
    k8s.apisix.apache.org/rewrite-target-regex-template: "/$2"
spec:
  ingressClassName: {{ getenv "INGRESS_CLASS" }}
  rules:
  - host: eoapi.{{ getenv "INGRESS_HOST" }}
    http:
      paths:
      - path: /vector(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: vector
            port:
              number: 8080
  {{- if eq ( getenv "HTTP_SCHEME" ) "https" }}
  tls:
  - hosts:
    - eoapi.{{ getenv "INGRESS_HOST" }}
    secretName: eoapi-tls
  {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eoapi-stac-manager
  namespace: data-access
  annotations:
    {{- range $key, $value := (datasource "annotations") }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
    k8s.apisix.apache.org/enable-cors: "true"
    k8s.apisix.apache.org/http-to-https: "true"
    k8s.apisix.apache.org/enable-websocket: "true"
spec:
  ingressClassName: {{ getenv "INGRESS_CLASS" }}
  rules:
  - host: eoapi.{{ getenv "INGRESS_HOST" }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: stac-manager
            port:
              number: 9000
  {{- if eq ( getenv "HTTP_SCHEME" ) "https" }}
  tls:
  - hosts:
    - eoapi.{{ getenv "INGRESS_HOST" }}
    secretName: eoapi-tls
  {{- end }}
