#!/bin/bash

source ../common/utils.sh
source "${HOME}/.eoepca/state"

NAMESPACE="operations"

# Create namespace
kubectl create namespace "${NAMESPACE}" --dry-run=client -o yaml | kubectl apply -f -

# Loki S3 credentials
kubectl apply -n "${NAMESPACE}" -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: loki-s3-credentials
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "${S3_ACCESS_KEY}"
  AWS_SECRET_ACCESS_KEY: "${S3_SECRET_KEY}"
EOF
echo "✅ Secret 'loki-s3-credentials' applied."

# oauth2-proxy cookie secret
kubectl apply -n "${NAMESPACE}" -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: keep-oauth2-proxy-cookie
type: Opaque
stringData:
  cookie-secret: "${OAUTH2_PROXY_COOKIE_SECRET}"
EOF
echo "✅ Secret 'keep-oauth2-proxy-cookie' applied."

# IAM client secret stubs
# If IAM is enabled, create empty stubs that will be populated later
# with the actual client secrets generated by Keycloak.
if [ "${OPERATIONS_ENABLE_IAM}" = "yes" ]; then

    if ! kubectl -n "${NAMESPACE}" get secret monitoring-oidc >/dev/null 2>&1; then
        kubectl apply -n "${NAMESPACE}" -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-oidc
type: Opaque
stringData:
  attribute.client_secret: "CHANGEME_POPULATE_FROM_KEYCLOAK"
EOF
        echo "⚠️  Secret 'monitoring-oidc' created as a placeholder."
        echo "    Populate 'attribute.client_secret' with the real value from Keycloak"
        echo "    then restart the Grafana pod."
    fi

    if ! kubectl -n "${NAMESPACE}" get secret alerting-oidc >/dev/null 2>&1; then
        kubectl apply -n "${NAMESPACE}" -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: alerting-oidc
type: Opaque
stringData:
  attribute.client_secret: "CHANGEME_POPULATE_FROM_KEYCLOAK"
EOF
        echo "⚠️  Secret 'alerting-oidc' created as a placeholder."
        echo "    Populate 'attribute.client_secret' with the real value from Keycloak"
        echo "    then restart the keep-oauth2-proxy pod."
    fi
fi

# Keep backend auth secrets
# Keep expects a secret named keep-auth-secrets referenced by envFromSecret in its values.
# Create an empty one if it doesn't exist so the Keep chart can install cleanly.
if ! kubectl -n "${NAMESPACE}" get secret keep-auth-secrets >/dev/null 2>&1; then
    kubectl create secret generic keep-auth-secrets -n "${NAMESPACE}"
    echo "✅ Empty secret 'keep-auth-secrets' created (populate if Keep needs additional env vars)."
fi

echo "✅ All secrets applied."