#!/usr/bin/env bash

ORIG_DIR="$(pwd)"
cd "$(dirname "$0")"
BIN_DIR="$(pwd)"

onExit() {
  cd "${ORIG_DIR}"
}
trap onExit EXIT

source ./userman-options

cluster_name="${1:-eoepca}"

../eoepca/eoepca.sh apply ${cluster_name} ${domain} ${public_ip}
