#!/usr/bin/env bash

ORIG_DIR="$(pwd)"
cd "$(dirname "$0")"
BIN_DIR="$(pwd)"

onExit() {
  cd "${ORIG_DIR}"
}
trap onExit EXIT

source ./userman-options

eric_id="c6273327-11c0-4201-b507-d9d42bddce33"
bob_id="f1867f17-0d54-497a-9105-412f95f7fc65"

../eoepca/eoepca-protection.sh apply "${eric_id}" "${bob_id}" "${public_ip}" "${domain}"
