image:
  registry: docker.io
  repository: bitnamilegacy/zookeeper
  tag: 3.8.1-debian-11-r18
global:
  storageClass: "{{ getenv "PERSISTENT_STORAGECLASS" }}"
replicacount: 1
autopurge:
  purgeInterval: 1
persistence:
  storageClass: "{{ getenv "PERSISTENT_STORAGECLASS" }}"
  size: 5Gi
resources:
  requests:
    memory: 1024Mi
