- name: Custom-Config
  resource:
    url: https://finder.creodias.eu/resto/api/collections/Landsat8/describe.xml
    type: OpenSearch
    query:
      bbox: -11.008301,49.880478,2.021484,59.478569
      collection: null
      time:
        begin: "2022-08-01T00:00:00Z"
        end: "2022-09-01T00:00:00Z"
        property: sensed
    format_config:
      property_mapping:
        end_datetime: completionDate
        productIdentifier: productIdentifier
        start_datetime: startDate
      type: application/json
  postprocess:
    - type: harvester_eoepca.postprocess.CREODIASOpenSearchLandsat8Postprocessor
  queue: register
  filter: {}