global:
  namespace: default
ingress:
  enabled: false
db:
  volume_storage_type: $DB_STORAGE_CLASS
  config:
    enabled: true
pycsw:
  config:
    server:
      url: https://resource-catalogue.$INGRESS_HOST