global:
  namespace: resource-catalogue
ingress:
  enabled: true
  name: resource-catalogue
  host: resource-catalogue.$INGRESS_HOST
  tls_host: resource-catalogue.$INGRESS_HOST
  tls_secret_name: resource-catalogue-tls
  class: nginx
  className: nginx
  annotations:
    ${CLUSTER_ISSUER_ANNOTATION}

db:
  volume_storage_type: $STORAGE_CLASS
  config:
    enabled: true
pycsw:
  config:
    server:
      url: $HTTP_SCHEME://resource-catalogue.$INGRESS_HOST