apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: workspace-charts
    namespace: ${NAMESPACE}
    files:
      - template-hr-data-access.yaml
      - template-hr-resource-catalogue.yaml
      - template-hr-resource-protection.yaml
      - template-cm-aws-config.yaml
      - template-cm-aws-credentials.yaml
      - template-cm-docker-config.yaml
generatorOptions:
  disableNameSuffixHash: true
