apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: workspace-charts
    namespace: ${NAMESPACE}
    files:
      - template-hr-vs.yaml
      - template-hr-rm-resource-catalogue.yaml
      - template-hr-resource-guard.yaml
generatorOptions:
  disableNameSuffixHash: true
