apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: resource-guard
spec:
  interval: 5m
  chart:
    spec:
      chart: resource-guard
      version: 1.2.5
      sourceRef:
        kind: HelmRepository
        name: eoepca
        namespace: ${NAMESPACE}
  values:
    #---------------------------------------------------------------------------
    # Global values
    #---------------------------------------------------------------------------
    global:
      context: "{{ workspace_name }}"
      domain: ${domain}
      nginxIp: ${public_ip}
      certManager:
        clusterIssuer: ${TLS_CLUSTER_ISSUER}
      default_owner: {{ default_owner }} # NOTE: do not remove, we need to store this here for redeploys
    #---------------------------------------------------------------------------
    # PEP values
    #---------------------------------------------------------------------------
    pep-engine:
      configMap:
        asHostname: auth
        pdpHostname: auth
      volumeClaim:
        name: "{{ workspace_name }}-pep-pvc"
        create: "true"
      defaultResources:
        - name: "Workspace {{ workspace_name }} Root"
          description: "Root URL of a users workspace"
          resource_uri: "/"
          scopes: []
          default_owner: {{ default_owner }}
    #---------------------------------------------------------------------------
    # UMA User Agent values
    #---------------------------------------------------------------------------
    uma-user-agent:
      nginxIntegration:
        enabled: true
        hosts:
          - host: "resource-catalogue.{{ workspace_name }}"
            paths:
              - path: "/(.*)"
                service:
                  name: "resource-catalogue-service"
                  port: 80
          - host: "data-access.{{ workspace_name }}"
            paths:
              - path: "/(ows.*)"
                service:
                  name: "vs-renderer"
                  port: 80
              - path: "/(opensearch.*)"
                service:
                  name: "vs-renderer"
                  port: 80
              - path: /(coverages/metadata.*)
                service:
                  name: data-access-renderer
                  port: 80
              - path: "/(admin.*)"
                service:
                  name: "vs-renderer"
                  port: 80
              - path: "/cache/(.*)"
                service:
                  name: "vs-cache"
                  port: 80
              - path: "/(.*)"
                service:
                  name: "vs-client"
                  port: 80
        annotations:
          nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
          nginx.ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/rewrite-target: "/$1"
      client:
        credentialsSecretName: "${UMA_CLIENT_SECRET}"
      logging:
        level: info
      unauthorizedResponse: 'Bearer realm="https://portal.${domain}/oidc/authenticate/"'
      openAccess: false
      insecureTlsSkipVerify: true
    #---------------------------------------------------------------------------
    # END values
    #---------------------------------------------------------------------------
