apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rm-resource-catalogue
spec:
  interval: 60m
  chart:
    spec:
      chart: rm-resource-catalogue
      version: 1.1.0
      sourceRef:
        kind: HelmRepository
        name: eoepca
        namespace: ${NAMESPACE}
  values:
    global:
      namespace: "{{ workspace_name }}"
    db:
      volume_storage_type: standard
    ingress:
      enabled: ${OPEN_INGRESS}
      name: ${nameResourceCatalogue}
      host: ${nameResourceCatalogue}.{{ workspace_name }}.${domain}
      tls_host: ${nameResourceCatalogue}.{{ workspace_name }}.${domain}
      tls_secret_name: ${nameResourceCatalogue}-{{ workspace_name }}-tls
    pycsw:
      config:
        server:
          url: "https://${nameResourceCatalogue}.{{ workspace_name }}.${domain}"
        # ???: do we need a `metadata` element?
        # metadata: {}
        # ???: do we need a `inspire` element?
        # inspire: {}
