rootUser: ${MINIO_USER}
rootPassword: ${MINIO_PASSWORD}
replicas: 2
ingress:
  enabled: true
  ingressClassName: ${INGRESS_CLASS}
  annotations:
${CUSTOM_INGRESS_ANNOTATIONS}
    k8s.apisix.apache.org/enable-websocket: "true"
  path: /
  hosts:
    - minio.${INGRESS_HOST}
  tls:
    - secretName: minio-tls
      hosts:
        - minio.${INGRESS_HOST}
consoleIngress:
  enabled: true
  ingressClassName: ${INGRESS_CLASS}
  annotations:
${CUSTOM_INGRESS_ANNOTATIONS}
    k8s.apisix.apache.org/enable-websocket: "true"
  path: /
  hosts:
    - console-minio.${INGRESS_HOST}
  tls:
    - secretName: minio-console-tls
      hosts:
        - console-minio.${INGRESS_HOST}
resources:
  requests:
    memory: 1Gi
persistence:
  storageClass: ${STORAGE_CLASS}
  size: 50Gi
buckets:
  - name: eoepca
  - name: cache-bucket
  - name: gitlab-backup-storage
  - name: gitlab-tmp-storage
  - name: gitlab-lfs-storage
  - name: mlopbb-mlflow-sharinghub
  - name: mlopbb-sharinghub
