rootUser: {{ getenv "MINIO_USER" }}
rootPassword: {{ getenv "MINIO_PASSWORD" }}
replicas: 2
ingress:
  enabled: true
  ingressClassName: {{ getenv "INGRESS_CLASS" }}
  annotations:
    {{- if eq (getenv "INGRESS_CLASS") "apisix" }}
    k8s.apisix.apache.org/enable-websocket: "true"
    {{- end }}

    {{- range $key, $value := (datasource "annotations") }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
  path: /
  hosts:
    - minio.{{ getenv "INGRESS_HOST" }}
  tls:
    - secretName: minio-tls
      hosts:
        - minio.{{ getenv "INGRESS_HOST" }}
consoleIngress:
  enabled: true
  ingressClassName: {{ getenv "INGRESS_CLASS" }}
  annotations:
    {{- if eq (getenv "INGRESS_CLASS") "apisix" }}
    k8s.apisix.apache.org/enable-websocket: "true"
    {{- end }}

    {{- range $key, $value := (datasource "annotations") }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
  path: /
  hosts:
    - console-minio.{{ getenv "INGRESS_HOST" }}
  tls:
    - secretName: minio-console-tls
      hosts:
        - console-minio.{{ getenv "INGRESS_HOST" }}
resources:
  requests:
    memory: 1Gi
persistence:
  storageClass: {{ getenv "STORAGE_CLASS" }}
  size: 50Gi
buckets:
  - name: eoepca
  - name: cache-bucket
  - name: gitlab-backup-storage
  - name: gitlab-tmp-storage
  - name: gitlab-lfs-storage
  - name: mlopbb-mlflow-sharinghub
  - name: mlopbb-sharinghub
