apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opa
  namespace: iam
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    {{- range $key, $value := (datasource "annotations") }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - opa.{{ getenv "INGRESS_HOST" }}
      secretName: opa-tls
  rules:
    - host: opa.{{ getenv "INGRESS_HOST" }}
      http:
        paths:
          - path: /healthcheck
            pathType: Prefix
            backend:
              service:
                name: opa-opal-client
                port:
                  number: 7000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: opa-opal-client
                port:
                  number: 8181
